In [1]:
import numpy as np

from src.statistical_analysis import block

In [2]:
import matplotlib.pyplot as plt

## Analysis for non-interactive case

In [3]:
N_vals = [1, 10, 100, 500]
d_vals = [1, 2, 3]
mean_values = np.zeros((len(N_vals), len(d_vals)))
var_values = np.zeros((len(N_vals), len(d_vals)))


for i, N in enumerate(N_vals):
    for j, d in enumerate(d_vals):
        print(".", end=" ")
        filename = f"output/temp_energy_statistics_N={N}_d={d}_no_interactions.csv"
        E = np.loadtxt(filename)
        mean_values[i, j] = np.mean(E)
        var_values[i, j] = block(E)

print()


. . . . . . . . . . . . 


In [4]:
print("Mean values:")
print(mean_values)

print()
print("Standard errors:")
print(np.sqrt(var_values))

Mean values:
[[5.00000047e-01 9.99999892e-01 1.50000024e+00]
 [4.99999992e+00 9.99999989e+00 1.49999998e+01]
 [4.99999998e+01 1.00000000e+02 1.50000000e+02]
 [2.49999999e+02 5.00000000e+02 7.50000011e+02]]

Standard errors:
[[2.28961364e-07 1.64327519e-07 1.25335911e-07]
 [2.21095961e-08 2.27639628e-08 5.15013474e-08]
 [6.07790169e-08 7.32919977e-08 1.59072847e-07]
 [3.38250816e-07 4.97714942e-08 1.61242239e-06]]


In [5]:
true_error = mean_values - 0.5 * np.array(N_vals).reshape(-1, 1) * np.array(d_vals).reshape(1, -1)

print(true_error)

[[ 4.72585545e-08 -1.08175593e-07  2.38587317e-07]
 [-7.70846231e-08 -1.12938080e-07 -2.16185596e-07]
 [-2.01387344e-07  1.41831592e-07  3.39876863e-07]
 [-5.08490899e-07 -1.06768425e-08  1.11333442e-05]]


In [6]:
print(true_error / np.sqrt(var_values))

[[ 0.20640406 -0.65829262  1.90358306]
 [-3.48647812 -4.96126624 -4.19766873]
 [-3.31343537  1.93515795  2.13661143]
 [-1.50329541 -0.21451722  6.90473183]]


In [16]:
# print mean values, standard errors and absolute errors in a latex table
print("\\begin{tabular}{c c c c c}")
print("\\hline")
print("d & N & Estimated energy & Estimated std. error & abs. error \\\\")
print("\\hline")
for j, d in enumerate(d_vals):
    for i, N in enumerate(N_vals):
        if i == 0:
            print(f"{d} & {N} & ${mean_values[i, j]:.2E}}}$ & ${np.sqrt(var_values[i, j]):.2E}}}$ & ${true_error[i, j]:.2E}}}$ \\\\".replace("E", "\\cdot 10^{"))
        else:
            print(f" & {N} & ${mean_values[i, j]:.2E}}}$ & ${np.sqrt(var_values[i, j]):.2E}}}$ & ${true_error[i, j]:.2E}}} $\\\\".replace("E", "\\cdot 10^{"))
print("\\hline")
print("\\end{tabular}")


\begin{tabular}{c c c c c}
\hline
d & N & Estimated energy & Estimated std. error & abs. error \\
\hline
1 & 1 & $5.00\cdot 10^{-01}$ & $2.29\cdot 10^{-07}$ & $4.73\cdot 10^{-08}$ \\
 & 10 & $5.00\cdot 10^{+00}$ & $2.21\cdot 10^{-08}$ & $-7.71\cdot 10^{-08} $\\
 & 100 & $5.00\cdot 10^{+01}$ & $6.08\cdot 10^{-08}$ & $-2.01\cdot 10^{-07} $\\
 & 500 & $2.50\cdot 10^{+02}$ & $3.38\cdot 10^{-07}$ & $-5.08\cdot 10^{-07} $\\
2 & 1 & $1.00\cdot 10^{+00}$ & $1.64\cdot 10^{-07}$ & $-1.08\cdot 10^{-07}$ \\
 & 10 & $1.00\cdot 10^{+01}$ & $2.28\cdot 10^{-08}$ & $-1.13\cdot 10^{-07} $\\
 & 100 & $1.00\cdot 10^{+02}$ & $7.33\cdot 10^{-08}$ & $1.42\cdot 10^{-07} $\\
 & 500 & $5.00\cdot 10^{+02}$ & $4.98\cdot 10^{-08}$ & $-1.07\cdot 10^{-08} $\\
3 & 1 & $1.50\cdot 10^{+00}$ & $1.25\cdot 10^{-07}$ & $2.39\cdot 10^{-07}$ \\
 & 10 & $1.50\cdot 10^{+01}$ & $5.15\cdot 10^{-08}$ & $-2.16\cdot 10^{-07} $\\
 & 100 & $1.50\cdot 10^{+02}$ & $1.59\cdot 10^{-07}$ & $3.40\cdot 10^{-07} $\\
 & 500 & $7.50\cdot 10^{+