In [3]:
import numpy as np

from src.statistical_analysis import block

## Analysis for non-interactive case

In [9]:
filename = "output/energy_statistics_N=10_d=1_no_interactions.csv"

In [10]:
E = np.loadtxt(filename)

In [11]:
print(np.mean(E)/1)
print(block(E))


5.000003638584615
4.899749872938588e-13


In [14]:
N_vals = [1, 10, 100, 500]
d_vals = [1, 2, 3]
mean_values = np.zeros((len(N_vals), len(d_vals)))
var_values = np.zeros((len(N_vals), len(d_vals)))


for i, N in enumerate(N_vals):
    for j, d in enumerate(d_vals):
        print(".", end=" ")
        filename = f"output/energy_statistics_N={N}_d={d}_no_interactions.csv"
        E = np.loadtxt(filename)
        mean_values[i, j] = np.mean(E)
        var_values[i, j] = block(E)

print()


. . . . . . . . . . . . 


In [17]:
print("Mean values:")
print(mean_values)

print()
print("Standard errors:")
print(np.sqrt(var_values))

Mean values:
[[4.99999890e-01 9.99999983e-01 1.50000012e+00]
 [4.99999993e+00 9.99999638e+00 1.49999998e+01]
 [4.99999998e+01 9.99999290e+01 1.49999990e+02]
 [2.50000000e+02 5.00000000e+02 7.50000010e+02]]

Standard errors:
[[2.13184597e-07 1.76146829e-07 1.28637802e-07]
 [2.48834870e-08 2.48002728e-08 5.28707956e-08]
 [6.34553570e-08 4.91441494e-08 1.23435676e-07]
 [2.96775614e-07 5.18414633e-10 1.59664975e-06]]


In [20]:
true_error = mean_values - 0.5 * np.array(N_vals).reshape(-1, 1) * np.array(d_vals).reshape(1, -1)

print(true_error)

[[-1.09721184e-07 -1.70873387e-08  1.17141009e-07]
 [-6.74176270e-08 -3.61714124e-06 -1.95300565e-07]
 [-2.07197651e-07 -7.09665774e-05 -9.77671152e-06]
 [-2.89678468e-07 -2.26486918e-09  1.04296211e-05]]
